baseURL = "https://tenach.github.io/"
languageCode = "en-us"
title = "Tenach - 推那墙"

# include content marked as draft
buildDrafts = false

# include content with publishdate in the future
buildFuture = false

# include content already expired
buildExpired = false

# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
canonifyURLs = true

disqusShortname = "tenach"

# theme to use (located by default in /themes/THEMENAME/)
themesDir = "themes"
theme = "hugo-lithium-theme"

[params]
    [params.logo]
    url = "fist.png"
    width = 50
    height = 50
    alt = "Logo"

[[menu.main]]
    name = "Articles"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
